docs: simplify wording
dipe/free-radical-specification pull request #2
Opened 2016-12-10 17:27 UTC by marionebl

2016-12-11 09:54 UTC, KnisterPeter requested changes

2016-12-11 09:54 UTC, KnisterPeter commented on mission-statement.md
> +force open encrusted processes and
What do you mean by "force open encrusted processes".
You want to say that we open up encrusted processes?

2016-12-11 09:54 UTC, KnisterPeter commented on mission-statement.md
> +deconstruct gigantic scopes.
This is a bit over the top from my perspective.
Lets find a more realistic wording here.

2016-12-13 01:47 UTC, marionebl commented on mission-statement.md
> +force open encrusted processes and
"Force open" as in "He forced open a lock". I intended this to sound violent - "open up" would be the tamer variant. Your suggestion works, too.

2016-12-13 01:49 UTC, marionebl commented on mission-statement.md
> +deconstruct gigantic scopes.
What exactly feels over the top? The 

> ... legacy code bases, encrusted processes, gigantic scopes

are present in the current version.

2016-12-13 06:37 UTC, KnisterPeter approved these changes

2016-12-13 06:37 UTC, KnisterPeter commented on mission-statement.md
> +force open encrusted processes and
If you intended to sound that violent, then :+1:

2016-12-13 06:37 UTC, KnisterPeter commented on mission-statement.md
> +deconstruct gigantic scopes.
I've meant 'gigantic scopes'.
You are right, I've read over that phrase.

2017-03-19 11:07 UTC, marionebl commented
@kotzendekrabbe @dipe @helgri Please review, I'd like to go forward on this.

2017-10-18 04:42 UTC, marionebl commented
Going forward with this.

2017-10-18 04:42 UTC, merged